var host = {
	FSHARE: 	'fshare.vn',
	UPFILE: 	'upfile.vn',
	_4SHARE: 	'4share.vn',
	TENLUA: 	'tenlua.vn',
	MP3ZING: 	'mp3.zing.vn',
	TAILIEU: 	'tailieu.vn',
	NHACCUATUI: 'nhaccuatui.com',
	YOUTUBE: 	'youtube.com',
	MEDIAFIRE: 	'mediafire.com',
	IMGUR: 		'imgur.com',
	FLICKR: 	'flickr.com',
	SLIDESHARE: 'slideshare.net',
	GITHUB: 	'github.com',
	SCRIBD: 	'scribd.com',
	SOUNDCLOUD: 'soundcloud.com',
	VIMEO: 		'vimeo.com',
	DAILYMOTION:'dailymotion.com',
	NHACSO: 	'nhacso.net',
	DROPBOX:	'dropbox.com',
	VNDOC:		'vndoc.com',
	GOOGLEPLAY:	'play.google.com',
	DEEZER:		'deezer.com',
	APPVN:		'appvn.com',
	VIOLET: 	'violet.vn',
	XVIDEOS:	'xvideos.com',
	YOUJIZZ:	'youjizz.com',
	ZIPPYSHARE: 'zippyshare.com',
	_4SHARED:	'4shared.com',
	OPENLOAD:	'openload.co',
	PHIMMOI:	'phimmoi.net',
	GETT:		'ge.tt',
	APHIM:		'aphim.co',
	GOOGLEDOC:	'docs.google.com',
	ZINGTV:		'tv.zing.vn',
	TEVI:		'tevi.com',
	SUBSCENE:	'subscene.com',
	GFYCAT:		'gfycat.com',
	JAVHD:		'javhd.com',
	SHUTTERSTOCK: 'shutterstock.com',

	// Short link service
	ADFLY:		'adf.ly',
	TINYURL:	'tinyurl.com',
	GOOGL:		'goo.gl',
	BITLY:		'bitly.com',
	BITDO:		'bit.do',
	OWLY:		'ow.ly',
	TRIM:		'tr.im',
	COINURL:	'cur.lv',
	ITYIM:		'ity.im',
	ISGD:		'is.gd',
	UTO:		'u.to',
	CUTTUS:		'cutt.us',
	QRNET:		'qr.net',
	VGD:		'v.gd',
	ZIPNET:		'zip.net',
	_7LY:		'7.ly',
	ADMYLINK:	'admy.link',
	GOODLY:		'good.ly',
	LYNKMY:		'lynk.my',
	TINYCC:		'tiny.cc',
	SID:		's.id',
	PHDOG:		'ph.dog',
	LINKSHRINK:	'linkshrink.net',
	LINK5S:		'link5s.com'
}

module.exports = host
